# Generated by Django 4.2.3 on 2023-09-11 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=250, null=True, verbose_name='Человекопонятный URL')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Изображение')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2023, 9, 11, 20, 27, 52, 270779), verbose_name='Дата создания')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Запись в блоге',
                'verbose_name_plural': 'Записи в блоге',
                'ordering': ('-creation_date',),
            },
        ),
    ]
